Update veracode-policy-scan.yml

diff --git a/.github/workflows/veracode-policy-scan.yml b/.github/workflows/veracode-policy-scan.yml
--- a/.github/workflows/veracode-policy-scan.yml
+++ b/.github/workflows/veracode-policy-scan.yml
@@ -59,13 +59,11 @@ jobs:
           export VERACODE_API_KEY_SECRET=${{ secrets.API_KEY }}
           guid=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v1/applications?name=${{ github.event.client_payload.profile_name }}" | jq -r '._embedded.applications[] | select(.profile.name == "${{ github.event.client_payload.profile_name }}") | .guid')
           echo GUID: ${guid}
-          total_flaws=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v2/applications/${application.guid}/findings?scan_type=STATIC&violates_policy=True" | jq -r '.page.total_elements')
+          total_flaws=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v2/applications/${guid}/findings?scan_type=STATIC&violates_policy=True" | jq -r '.page.total_elements')
           echo TOTAL_FLAWS: ${total_flaws}
-          http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v2/applications/${application.guid}/findings?scan_type=STATIC&violates_policy=True&size=${total_flaws}" > policy_flaws.json
-          results_url=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v1/applications?name=${{ github.event.client_payload.profile_name }}" | jq -r '._embedded.applications[] | select(.profile.name == "${{ github.event.client_payload.profile_name }}") | .results_url')
-          echo "https://analysiscenter.veracode.com/auth/index.jsp#${results_url}" > results_url.txt
-          policy_compliance=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v1/applications?name=${{ github.event.client_payload.profile_name }}" | jq -r '._embedded.applications[] | select(.profile.name == "${{ github.event.client_payload.profile_name }}") | .profile.policies[0].policy_compliance_status')
-          echo COMPLIANCE: ${policy_compliance}
+          http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v2/applications/${guid}/findings?scan_type=STATIC&violates_policy=True&size=${total_flaws}" > policy_flaws.json
+          results_url=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v1/applications/${guid}" | jq -r '.results_url')
+          echo "https://analysiscenter.veracode.com/auth/index.jsp#${results_url}" > results_url.txt     
       - name: save results file
         uses: actions/upload-artifact@v3
         with:
@@ -73,3 +71,15 @@ jobs:
           path: |
             /tmp/policy_flaws.json
             /tmp/results_url.txt
+      - name: fair the pipeline for compliance
+        run: |
+          export VERACODE_API_KEY_ID=${{ secrets.API_ID }}
+          export VERACODE_API_KEY_SECRET=${{ secrets.API_KEY }}
+          policy_compliance=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v1/applications?name=${{ github.event.client_payload.profile_name }}" | jq -r '._embedded.applications[] | select(.profile.name == "${{ github.event.client_payload.profile_name }}") | .profile.policies[0].policy_compliance_status')
+          echo COMPLIANCE: ${policy_compliance}
+          if [ ${policy_compliance} == "DID_NOT_PASS" ]; then
+            echo "Compliance not met, pipeline fails"
+            exit 1
+          else
+            echo "Compliance met, pipeline continues"
+          fi
